#pragma config(Sensor, in1,    marbleReader,   sensorReflection)
#pragma config(Sensor, dgtl1,  stopButton,     sensorTouch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           bucketServo,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           latch,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum KindOfMarble {marble1, marble2, marble3};//declare the types of marbles

KindOfMarble getMarbleType()//set up the function to determine the type of marble
{
	KindOfMarble marbleType; //makes variable to store the type of marble
	int lightValue = SensorValue[marbleReader];//gets value from sensor

	if(lightValue < 1  && lightValue > 2 )//interprite the type of marble
	{
		marbleType = marble1;//sets the marble type to marble1
	}
	else if(lightValue < 1 && lightValue > 2 )//interprite the type of marble
	{
		marbleType = marble2;//sets the marble type to marble2
	}

	else
	{
		marbleType = marble3;//sets the marble type to marble4
	}

	return marbleType;//returns the type of marble
}

void releaseMarble()//creates function to release the marble
{
	motor[latch]=127;//opens gate
	wait(.5);//waits
	motor[latch]=-127;//closes gate
	wait(500);//waits
	motor[latch]=0;//stops motor
}

bool setConveyer(KindOfMarble marbleType)
{
	switch(marbleType)//sets up a system where it will decide what to do beased off of the marble type
	{
		case(marble1)://what to do in case of marble 1
		{
			setServo(bucketServo, 127);//set place to first bucket
			break;//exits switch
		}
		case(marble2)://what to do in case of marble 2
		{
			setServo(bucketServo, -127);//set place to second bucket
			break;//exits switch
		}
		case(marble3)://what to do in case of marble 3
		{
			setServo(bucketServo, 0);
			break;//exits switch
		}
	}
	wait(1);//waits to make sure the servo is in the right spot before releasing the marble
	return true; //tells the sorter the marble is ready to be released
}

task main()//execute the code
{
	KindOfMarble nextMarble;//declares a variable saying what the next marble type is
	bool canGo;//creates a boolean that lets the system know when it can release the next marble
	releaseMarble();//release marble
	while(SensorValue[stopButton]==false)//run while the stop button isnt pressed
	{
		nextMarble = getMarbleType();//get the next marble type
		canGo = setConveyer(nextMarble);//set servo to new position
		while(canGo == false)//wait until servo is done
		{

		}
		releaseMarble();//release marble
}
}
